# Generated by Django 3.1.7 on 2023-03-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_address', models.CharField(default='', max_length=256)),
                ('end_address', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
